### ISSUE TITLE
Back to my learning curve questions ...

### ISSUE THREAD

**Issue by dragonfaerie** [tomizechsterson/chargen-rails#11]
I think I have a (rough) plan on how to do theming.  However, that requires me adding in more stylesheets and probably some javascript.  This may be my exhaustion speaking but I can not figure out how to add new stylesheets.

**Comment by tomizechsterson** [comment]
Did you end up figuring this out? If so, I would only ask that you don't make an scss file named `custom.scss` since that's what I'm using for the header with this auth stuff. Naturally, that can all go wherever once it's merged; just want to avoid any merge conflicts

**Comment by dragonfaerie** [comment]
I have not figured it out. Not sure what I'm doing wrong.  Aren't headers normally like nav or something? :) But no, I wasn't going to use custom.scss

**Comment by tomizechsterson** [comment]
Ok cool. We can go over this at lunch at some point (hopefully Friday)

**Comment by dragonfaerie** [comment]
Figured this out! :)
