### ISSUE TITLE
Figure out theming

### ISSUE THREAD

**Issue by dragonfaerie** [tomizechsterson/chargen-rails#16]

**Comment by dragonfaerie** [comment]
I think I've figured out theming.  Yes, settling on a color scheme and font will lead to tweaking the current set up but for now I think it's set. Should I close this?  Or do I spin off sub ... issue?  Learning curves ;)

**Comment by tomizechsterson** [comment]
Yeah, this should be good, and you could definitely open up some more issues for things you know we'll need. You can also add to your PR's description something like `resolves #16` or `closes #16` and this issue will automatically close and move the card on the board to done when the PR gets merged. #12 shows how I typically do it

**Comment by dragonfaerie** [comment]
Addresses #16, will add future cards to fine tune the base design
