### ISSUE TITLE
Webpacker hates me

### ISSUE THREAD

**Issue by dragonfaerie** [tomizechsterson/chargen-rails#3]
<img width="1132" alt="Screen Shot 2021-03-19 at 12 28 47 PM" src="https://user-images.githubusercontent.com/22320727/111819778-bf4b4400-88ae-11eb-9f0a-d83e321072f6.png">

**Comment by tomizechsterson** [comment]
Do you happen to have a `public/packs/js/manifest.json` file by any chance?

**Comment by dragonfaerie** [comment]
Actually I don't.  What would I do to fix this?

**Comment by tomizechsterson** [comment]
Ah ok, let's try running `yarn` at the root of the project and see if that appears. If so, I bet that was the issue

**Comment by dragonfaerie** [comment]
Yarn. Of course.  I'm operational now.  Learning curve, I have a big one!  Thanks.

**Comment by tomizechsterson** [comment]
lol no worries; glad that helped. I've also updated the readme, so this doesn't happen again
