### ISSUE TITLE
Add Basic Auth

### ISSUE THREAD

**Issue by tomizechsterson** [tomizechsterson/chargen-rails#5]
Add ability to sign up via email and store first name, last name, email, password

Also implement basic authorization:
* [x] Users shouldn't be able to see each other's characters
* [x] Anonymous users shouldn't see anything, and be encouraged to sign up or sign in
* [x] Admin users should see all characters
* [x] Admin users should be able to see which user a character belongs to

**Comment by dragonfaerie** [comment]
Will the user auth include like a user profile area?  Reason I'm asking is with the theming I'll need a toggle to swap modes and that feels user profile-ish.

**Comment by tomizechsterson** [comment]
Yup, that's the intent. I'll have a profile page included with all this
