### ISSUE TITLE
Add more character information fields to the database

### ISSUE THREAD

**Issue by dragonfaerie** [tomizechsterson/chargen-rails#7]
Need a lot more than just name. :)

**Comment by tomizechsterson** [comment]
Yup, for sure. We just need to decide on how we want to design the character creation process, since that pretty much drives everything else, and I'm not picky on how we want that to look for the user

**Comment by dragonfaerie** [comment]
That makes sense.  I'm jumping all over the place again aren't I lol

**Comment by tomizechsterson** [comment]
lol nah, it's all good. I'm pretty sure that's common at the start of a project. Especially if there isn't a lot of up-front design work. We're sort of doing that as we go

**Comment by dragonfaerie** [comment]
put a card on board to remember work
