### ISSUE TITLE
pushing to master

### ISSUE THREAD

**Issue by dragonfaerie** [tomizechsterson/chargen-rails#8]
This falls under learning curve. :). Made progress on the error messages.  Now it's saying my master is behind what's in github so it rejected the push.  Is this when I use rebase?  Or what is the proper way of handling this?
<img width="663" alt="Screen Shot 2021-03-21 at 12 27 55 PM" src="https://user-images.githubusercontent.com/22320727/111914876-dbcbb580-8a41-11eb-9645-45f155d2465a.png">

**Comment by tomizechsterson** [comment]
Ah,  yes, this will probably need something like a `git rebase origin/master`. Try that and see if that helps

**Comment by dragonfaerie** [comment]
AHA I think I got it to push!  All I did in this was some css, and changed out the table for divs and classes.  Thanks!

**Comment by tomizechsterson** [comment]
Awesome! Is this ticket ok to close then?

**Comment by dragonfaerie** [comment]
It's all good! :)
